# Generated by Django 5.0.1 on 2024-01-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0005_haqida_photo_remove_news_photo_news_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='viewed_list',
            field=models.IntegerField(default=0),
        ),
    ]
